(()=>{var t={};t.id=9807,t.ids=[9807],t.modules={399:t=>{"use strict";t.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:t=>{"use strict";t.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},4770:t=>{"use strict";t.exports=require("crypto")},7702:t=>{"use strict";t.exports=require("events")},2615:t=>{"use strict";t.exports=require("http")},8791:t=>{"use strict";t.exports=require("https")},8216:t=>{"use strict";t.exports=require("net")},8621:t=>{"use strict";t.exports=require("punycode")},6162:t=>{"use strict";t.exports=require("stream")},2452:t=>{"use strict";t.exports=require("tls")},7360:t=>{"use strict";t.exports=require("url")},1568:t=>{"use strict";t.exports=require("zlib")},8359:()=>{},3739:()=>{},9341:(t,e,s)=>{"use strict";s.r(e),s.d(e,{originalPathname:()=>p,patchFetch:()=>m,requestAsyncStorage:()=>n,routeModule:()=>f,serverHooks:()=>h,staticGenerationAsyncStorage:()=>d});var a={};s.r(a),s.d(a,{GET:()=>c});var i=s(9303),l=s(8716),r=s(670),u=s(7070);let o=(0,s(843).eI)("https://rgfxyraamghqnechkppg.supabase.co",process.env.SUPABASE_SERVICE_ROLE_KEY||"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnZnh5cmFhbWdocW5lY2hrcHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODg5NzAsImV4cCI6MjA2ODI2NDk3MH0.hqoXq2YAs6cc96d0baVjZWVdmDW0qytCIHjA-YffSdk");async function c(){try{let{data:t,error:e}=await o.from("fetch_logs").select(`
        id,
        fetch_type,
        status,
        created_at,
        duration_ms,
        feed_id,
        feeds!inner(title)
      `);if(e)throw e;let s=new Date,a=new Date(s.getFullYear(),s.getMonth(),s.getDate()),i=new Date(s.getFullYear(),s.getMonth(),1),l={today:{auto:{total:0,successful:0,failed:0},manual:{total:0,successful:0,failed:0}},thisMonth:{auto:{total:0,successful:0,failed:0},manual:{total:0,successful:0,failed:0}},lifetime:{auto:{total:0,successful:0,failed:0},manual:{total:0,successful:0,failed:0}}},r=new Map;t?.forEach(t=>{let e=new Date(t.created_at),s="lifetime";if(e>=a?s="today":e>=i&&(s="thisMonth"),"attempt"!==t.status){let e=t.fetch_type;l[s][e].total++,l.lifetime[e].total++,"success"===t.status?(l[s][e].successful++,l.lifetime[e].successful++):"failure"===t.status&&(l[s][e].failed++,l.lifetime[e].failed++),"today"===s&&(l.thisMonth[e].total++,"success"===t.status?l.thisMonth[e].successful++:"failure"===t.status&&l.thisMonth[e].failed++)}let u=t.feed_id;r.has(u)||r.set(u,{feedId:t.feed_id,feedTitle:t.feeds.title,today:{auto:{total:0,successful:0,failed:0,durations:[]},manual:{total:0,successful:0,failed:0,durations:[]}},thisMonth:{auto:{total:0,successful:0,failed:0,durations:[]},manual:{total:0,successful:0,failed:0,durations:[]}},lifetime:{auto:{total:0,successful:0,failed:0,durations:[]},manual:{total:0,successful:0,failed:0,durations:[]}}});let o=r.get(u);"attempt"!==t.status&&(o[s][t.fetch_type].total++,o.lifetime[t.fetch_type].total++,"success"===t.status?(o[s][t.fetch_type].successful++,o.lifetime[t.fetch_type].successful++,t.duration_ms&&(o[s][t.fetch_type].durations.push(t.duration_ms),o.lifetime[t.fetch_type].durations.push(t.duration_ms))):"failure"===t.status&&(o[s][t.fetch_type].failed++,o.lifetime[t.fetch_type].failed++),"today"===s&&(o.thisMonth[t.fetch_type].total++,"success"===t.status?(o.thisMonth[t.fetch_type].successful++,t.duration_ms&&o.thisMonth[t.fetch_type].durations.push(t.duration_ms)):"failure"===t.status&&o.thisMonth[t.fetch_type].failed++))});let{data:c,error:f}=await o.from("fetch_logs").select(`
        feeds!inner(title)
      `).eq("status","failure").gte("created_at",i.toISOString());if(f)throw f;let n=new Map;c?.forEach(t=>{let e=t.feeds.title;n.set(e,(n.get(e)||0)+1)});let d=Array.from(n.entries()).map(([t,e])=>({feedTitle:t,failureCount:e})).sort((t,e)=>e.failureCount-t.failureCount).slice(0,5),{data:h,error:p}=await o.from("fetch_logs").select(`
        article_id,
        articles!inner(title, url),
        feeds!inner(title),
        error_reason,
        created_at
      `).eq("status","failure").order("created_at",{ascending:!1}).limit(5);if(p)throw p;let m=t=>{let e=t.auto.total+t.manual.total,s=t.auto.successful+t.manual.successful,a=t.auto.failed+t.manual.failed;return{total:e,successful:s,failed:a,successRate:e>0?Math.round(s/e*1e3)/10:0,auto:{total:t.auto.total,successful:t.auto.successful,failed:t.auto.failed},manual:{total:t.manual.total,successful:t.manual.successful,failed:t.manual.failed}}},y=Array.from(r.values()).filter(t=>t.lifetime.auto.total+t.lifetime.manual.total>0).sort((t,e)=>{let s=t.lifetime.auto.total+t.lifetime.manual.total;return e.lifetime.auto.total+e.lifetime.manual.total-s}).map(t=>{let e=t=>{if(0===t.length)return null;let e=t.reduce((t,e)=>t+e,0);return Math.round(e/t.length)},s=t=>{let s=t.auto,a=t.manual,i=s.total+a.total,l=s.successful+a.successful,r=s.failed+a.failed,u=[...s.durations,...a.durations];return{total:i,successful:l,failed:r,successRate:i>0?Math.round(l/i*1e3)/10:0,auto:{total:s.total,successful:s.successful,failed:s.failed},manual:{total:a.total,successful:a.successful,failed:a.failed},avgDurationMs:e(u)}};return{feedId:t.feedId,feedTitle:t.feedTitle,today:s(t.today),thisMonth:s(t.thisMonth),lifetime:s(t.lifetime)}}),_=h?.map(t=>({articleId:t.article_id,articleTitle:t.articles.title,feedTitle:t.feeds.title,errorReason:t.error_reason,originalUrl:t.articles.url,timestamp:t.created_at}))||[];return u.NextResponse.json({overall:{today:m(l.today),thisMonth:m(l.thisMonth),lifetime:m(l.lifetime)},feeds:y,topIssues:{problematicFeeds:d,recentFailures:_}})}catch(t){return console.error("Fetch stats error:",t),u.NextResponse.json({error:"Failed to get fetch statistics",details:t instanceof Error?t.message:"Unknown error"},{status:500})}}let f=new i.AppRouteRouteModule({definition:{kind:l.x.APP_ROUTE,page:"/api/analytics/fetch-stats/route",pathname:"/api/analytics/fetch-stats",filename:"route",bundlePath:"app/api/analytics/fetch-stats/route"},resolvedPagePath:"/Users/shayon/DevProjects/rss-news-reader/src/app/api/analytics/fetch-stats/route.ts",nextConfigOutput:"",userland:a}),{requestAsyncStorage:n,staticGenerationAsyncStorage:d,serverHooks:h}=f,p="/api/analytics/fetch-stats/route";function m(){return(0,r.patchFetch)({serverHooks:h,staticGenerationAsyncStorage:d})}}};var e=require("../../../../webpack-runtime.js");e.C(t);var s=t=>e(e.s=t),a=e.X(0,[9276,5972,843],()=>s(9341));module.exports=a})();