"use strict";(()=>{var t={};t.id=3716,t.ids=[3716],t.modules={399:t=>{t.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:t=>{t.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},1970:(t,e,s)=>{s.r(e),s.d(e,{originalPathname:()=>h,patchFetch:()=>f,requestAsyncStorage:()=>l,routeModule:()=>p,serverHooks:()=>m,staticGenerationAsyncStorage:()=>d});var o={};s.r(o),s.d(o,{GET:()=>c});var r=s(9303),n=s(8716),i=s(670),a=s(7070),u=s(343);async function c(){let t=u.s.getConfig(),e=u.s.buildPrompt({title:"Sample Article Title",author:"Test Author",publishedDate:new Date().toLocaleDateString(),content:"This is sample article content for testing the prompt configuration..."});return a.NextResponse.json({currentConfig:t,environmentVariables:{SUMMARY_WORD_COUNT:process.env.SUMMARY_WORD_COUNT||"(not set - using default)",SUMMARY_FOCUS:process.env.SUMMARY_FOCUS||"(not set - using default)",SUMMARY_STYLE:process.env.SUMMARY_STYLE||"(not set - using default)"},defaultValues:{wordCount:"150-175",focus:"key facts, main arguments, and important conclusions",style:"objective"},samplePrompt:e.split("\n").slice(0,5).join("\n")+"..."})}let p=new r.AppRouteRouteModule({definition:{kind:n.x.APP_ROUTE,page:"/api/test-prompt-config/route",pathname:"/api/test-prompt-config",filename:"route",bundlePath:"app/api/test-prompt-config/route"},resolvedPagePath:"/Users/shayon/DevProjects/rss-news-reader/src/app/api/test-prompt-config/route.ts",nextConfigOutput:"",userland:o}),{requestAsyncStorage:l,staticGenerationAsyncStorage:d,serverHooks:m}=p,h="/api/test-prompt-config/route";function f(){return(0,i.patchFetch)({serverHooks:m,staticGenerationAsyncStorage:d})}},343:(t,e,s)=>{s.d(e,{s:()=>o});class o{static{this.DEFAULTS={wordCount:"150-175",focus:"key facts, main arguments, and important conclusions",style:"objective"}}static getConfig(){return{wordCount:process.env.SUMMARY_WORD_COUNT||this.DEFAULTS.wordCount,focus:process.env.SUMMARY_FOCUS||this.DEFAULTS.focus,style:process.env.SUMMARY_STYLE||this.DEFAULTS.style}}static buildPrompt(t){let e=this.getConfig();return`You are a news summarization assistant. Create a ${e.style} summary of the following article in ${e.wordCount} words. Focus on ${e.focus}. Maintain objectivity and preserve the author's core message.

IMPORTANT: Do NOT include the article title in your summary. Start directly with the content summary.

Article Details:
Title: ${t.title||"Untitled"}
Author: ${t.author||"Unknown"}
Published: ${t.publishedDate||"Unknown"}

Article Content:
${t.content}

Write a clear, informative summary that captures the essence of this article without repeating the title.`}}}};var e=require("../../../webpack-runtime.js");e.C(t);var s=t=>e(e.s=t),o=e.X(0,[9276,5972],()=>s(1970));module.exports=o})();